spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sesummer
    username: root
    password: BUAAYZH2001
  jpa:
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.example.SESummer.Entity
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080